### PR TITLE
Fix for issue/8 and s/xrange/enumerate/

### PR DESCRIPTION
**Pull request by a8**
Hi,

Hope this fixes https://github.com/vaidik/commentjson/issues/8 and doesn't introduce new bugs.
It comes with test json files.

I also replaced the for index in xrange(list(lines)) to enumerate(lines) which I find more readable. Doesn't change functionality. If you don't like it I'll send you a pull request for the 1st commit only.

F.

### CODE REVIEW

**Comment by a8** [comment]
May I ask if this code is still maintained? No offence but there are folks using it and suffering from bugs like that. With great code comes great responsibility ;-).

- a8

**Comment by vaidik** [comment]
@a8 So true. Really sorry about not being able to look at your PR. Been a bit busy and yes I have not been able to work on this. But knowing that people are using this code gives me motivation to be more careful. Thanks so much for that :)

**Comment by vaidik** [comment]
Thanks for the fix @a8 :)

**Comment by a8** [comment]
@vaidik no worries. Thanks for pulling. Yes, people use it :-), a lot actually since it solves a nagging problem.

**Pull request merged**
