### PR TITLE
python3.x compatibility

### PR DESCRIPTION
**Pull request by buxx**
Some changes to python 3.x. Working travis for following versions:

  - "2.6"
  - "2.7"
  - "3.2"
  - "3.4"
  - "3.5"

### CODE REVIEW

**Comment by girtsf** [comment]
FYI, this pull request makes it work on 3.5 for me.

**Comment by jrosebr1** [comment]
@vaidik Can this pull request please be merged in? Thanks!

**Comment by johanneswilm** [comment]
@buxx @girtsf @jrosebr1 It looks like @vaidik has become unresponsive (maybe dead?). What do you guys say toward creating a new pypi package and then continuing it there? We really need a pypi-released version that is compatible with Python3. The name really does not matter. @buxx would you be up for releasing a package called something like "strip-json-comments" or some other such thing with your code?

**Comment by jrosebr1** [comment]
@johanneswilm I'm interested but I wouldn't want to be the only maintainer as I'm quite busy. If others are willing to work on the project I would be willing to have the repo under my account.

**Comment by johanneswilm** [comment]
@jrosebr1 Great! I just found JSON.minify which seems to provide the same functionality and have the same issue [1]. Hopefully we can get one of the two projects up and running on pypi.


[1] https://github.com/getify/JSON.minify/issues/21

**Comment by johanneswilm** [comment]
@jrosebr1 It looks like the other project is willing to maintain the pypi package of JSON_minify [1]. And as far as I can tell, it provides the same functionality.

[1] https://pypi.python.org/pypi/JSON_minify

**Comment by buxx** [comment]
@johanneswilm Thank's for sharing, i will use JSON_minify to !

**Comment by jrosebr1** [comment]
@johanneswilm So to confirm, we're going to use JSON_minify now? Just want to make sure :-)

**Comment by johanneswilm** [comment]
I have switched, yes. There is now a current release of it on pypi and we have a way to get new releases out. Unless the situation with commentjson changes, I suggest we do that. It sounds like they are also open to give write access to more people should you be interested.

**Comment by gabyx** [comment]
Why is  this not merged :-)

**Comment by gabyx** [comment]
If @vaidik is no more responsing, there should be other maintainers who can merge this :-)

**Comment by johanneswilm** [comment]
@gabyx I don't know if there is a mechanism by which one can challenge package maintainership on pypi. For now the simplest is to switch to https://pypi.python.org/pypi/JSON_minify

**Comment by vaidik** [comment]
Hi Everyone,

Not dead just yet. :)

First of all, apologies for going missing for such a long time. I had just switched jobs around the time when conversations were going on here.

I had added support for python 3 a few months back. It should be possible for you to use commentjson with Python 3.

Supporting the library has been hard with my other commitments. If anyone of you wants to volunteer to maintain, I'd be more than happy to accept participation.

**Pull request closed without merging**
