### PR TITLE
python 2 + python 3 compatibility

### PR DESCRIPTION
**Pull request by Asher256**
Hi,

A pull request to help commentjson to be compatible with Python 2 and Python 3.

Asher256

### CODE REVIEW

**Comment by ChrisCummins** [comment]
@vaidik can this be merged?

**Comment by pzelasko** [comment]
@vaidik Please merge this.

**Comment by vaidik** [comment]
@Asher256 @ChrisCummins @pzelasko Apologies for having missed these and being one of those who don't maintain their projects. Merging this and making a release.

**Comment by ChrisCummins** [comment]
thanks :)

**Pull request merged**
